export { default as Main } from './Main'
export { default as About } from './About'
export { default as Blog } from './Blog'
export { default as Skill } from './Skill'
export { default as Work } from './Work'    
